# Buttons:
BUTTON_A = 0
BUTTON_B = 1
BUTTON_X = 2
BUTTON_Y = 3
BUTTON_GEAR_UP = 4
BUTTON_GEAR_DOWN = 5
BUTTON_MENU = 6
BUTTON_HOME = 7
BUTTON_RSB = 8
BUTTON_LSB = 9
BUTTON_XBOX = 10

BUTTON_VOL_UP = 18
BUTTON_VOL_DOWN = 19

BUTTON__CLKWISE = 20
BUTTON_CNTRCLKWISE = 21
BUTTON_ENTER = 22

# Axes:
AXIS_STEERING_WHEEL = 0
AXIS_ACCELERATOR = 1
AXIS_BRAKE = 2
AXIS_CLUTCH = 3

# Hats:
HAT_LEFT = (-1, 0)
HAT_RIGHT = (1, 0)
HAT_UP = (0, 1)
HAT_DOWN = (0, -1)
HAT_RELEASE = (0, 0)
